[package]
name = "stable-diffusion-webui-installer"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.10.4"
clap = { version = "4.2.7", features = ["cargo"] }
indicatif = "0.17.3"
reqwest = { version = "0.11.18", features = ["blocking"] }
