on:
  release:
    types: [created]

permissions: write-all

jobs:
  release:
    name: release ${{ github.event.release.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: "x86_64-unknown-linux-musl"
          EXTRA_FILES: "README.md LICENSE"
          MINIFY: true
          ARCHIVE_TYPES: "tar.gz"
