on:
  release:
    types: [created]

permissions: write-all

jobs:
  release:
    name: release ${{ github.event.release.tag_name }} ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl, x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Install OpenSSL
        run: sudo apt install libssl-dev openssl -y

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../sdinstaller-${{ matrix.target }}.tar.gz sdinstaller
          cd -
      
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: 'sdinstaller*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
